name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: npm run build
        env:
          # 必要な環境変数を指定
          GMAIL_USER: ${{ vars.GMAIL_USER }}
          INFO_USER: ${{ vars.INFO_USER }}
          REPLY_USER: ${{ vars.REPLY_USER }}
          TEST_USER: ${{ vars.TEST_USER }}
          INFO_PASS: ${{ secrets.INFO_PASS }}
          REPLY_PASS: ${{ secrets.REPLY_PASS }}

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # gh-pagesのpush先をトークン認証URLに書き換え
          npx gh-pages -d out -u "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -r https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
